lecture 1(https://www.youtube.com/watch?v=BzcBsTou0C0&feature=emb_logo)

In [2]:
import torch


tensor is basically just a way to represent a array.
to get shape use shape
to get a tensors of zeros use zeros

In [7]:
x = torch.tensor([1,2,3])
y = torch.tensor([2,3,9])
print(x*y)
z= torch.zeros([2,3])
print(z)
print(z.shape)

tensor([ 2,  6, 27])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


In [8]:
random= torch.rand([2,4])
print(random)

tensor([[0.0981, 0.3323, 0.8521, 0.6929],
        [0.9863, 0.2701, 0.8065, 0.5035]])


to reshape use view 

In [11]:
print(random)
random = random.view([8,1])
print(random)

tensor([[0.0981, 0.3323, 0.8521, 0.6929, 0.9863, 0.2701, 0.8065, 0.5035]])
tensor([[0.0981],
        [0.3323],
        [0.8521],
        [0.6929],
        [0.9863],
        [0.2701],
        [0.8065],
        [0.5035]])
